### ISSUE TITLE
2 Pion Channel Progression

### ISSUE THREAD

**Issue by trottan** [drewkenjo/common-analysis-topics#2]
1. produce root trees per each run- output 100s of root files (~200 in/out) contain 4 mom. of particles - run groovy script

**Comment by trottan** [comment]
[ntuple_ePipPimP.zip](https://github.com/drewkenjo/common-analysis-topics/files/7678796/ntuple_ePipPimP.zip)

Script to produce the root files for the two pion channel

**Comment by drewkenjo** [comment]
produce missing mass distributions for the e,p,pi+,pi- sample.

**Comment by trottan** [comment]
![EPipPimX](https://user-images.githubusercontent.com/40239907/145283234-fd29f6a7-78d1-494b-ae89-44f8d8f85c96.png)
![EPimPX](https://user-images.githubusercontent.com/40239907/145283264-8dc8ced8-044c-4657-9534-3943f175e209.png)
![EPipPX](https://user-images.githubusercontent.com/40239907/145283271-94375eb7-c8f6-4852-a526-822256e99e64.png)

**Comment by trottan** [comment]
![xbQ2_xbT](https://user-images.githubusercontent.com/40239907/145595294-71fb6265-fe3b-4b27-a836-bccf34d47fde.png)
![trentoPlots](https://user-images.githubusercontent.com/40239907/145595328-e9cb4a71-423d-4acd-92ec-9a8c7a77b983.png)

**Comment by trottan** [comment]
![EleKin](https://user-images.githubusercontent.com/40239907/145595460-8b41b0a7-f979-42eb-9ed3-0e33c2949f5f.png)
![PipKin](https://user-images.githubusercontent.com/40239907/145595491-6e73a77b-f19d-45ca-89a7-c2d7ff763bff.png)
![PimKin ](https://user-images.githubusercontent.com/40239907/145595503-52717c99-ed9d-4298-a8cd-1c46b07b875d.png)
![ProKin](https://user-images.githubusercontent.com/40239907/145597683-972b3dfb-7244-417b-a3ab-422a26888af4.png)
